# Generated by Django 5.1.6 on 2025-02-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllCars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
