# Generated by Django 5.1.6 on 2025-02-19 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllCars', '0004_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showroom', to='AllCars.showroom'),
        ),
    ]
